In [1]:
import networkx as nx

import pandas as pd
import numpy as np

import pickle

import community

In [2]:
pd.set_option('display.max_columns', 500)

In [3]:
with open('/Users/robertpagano/metis_data/project_5/final_raw_mccain_df.pickle', 'rb') as f:
    df_mccain = pickle.load(f)

In [4]:
df_mccain.head()

,tweet_id,user_id,display_name,screen_name,tweet_date,main_text,fav_count,rt_count,followers_count,is_verified,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,retweet_text,retweet_id,retweet_user_id,retweet_screen_name,retweet_is_verified,retweet_fav_count,retweet_followers_count,quoted_text,quoted_id,quoted_user_id,quoted_screen_name,quoted_is_verified,quoted_fav_count,is_retweet,is_quote
0,1109131638112432129,113817127,KDW,WYATT251,Fri Mar 22 16:36:03 +0000 2019,RT @thedilleyshow: Donald J. Trump is still Pr...,0,107,474,False,NaN,NaN,None,Donald J. Trump is still President.\n\nHillary...,1.109098e+18,1.085581e+18,thedilleyshow,False,299.0,8815.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
1,1109131636262744066,4839872717,Lou Ella Howard,ellahoward271,Fri Mar 22 16:36:03 +0000 2019,RT @LindseyGrahamSC: Great read. Spot on.\n\n...,0,65,3601,False,NaN,NaN,None,Great read. Spot on.\n\nMuch more could be sa...,1.109117e+18,4.328953e+08,LindseyGrahamSC,True,181.0,756904.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
2,1109131635742564352,881906625799266304,God Is LOVE,janetlchatham,Fri Mar 22 16:36:03 +0000 2019,RT @LouDobbs: #TrumpTrain- @RealDonaldTrump is...,0,158,153,False,NaN,NaN,None,#TrumpTrain- @RealDonaldTrump is speaking out ...,1.109129e+18,2.648717e+07,LouDobbs,True,366.0,1901004.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
3,1109131633603440640,242425184,Dominika Markova,dominikam42,Fri Mar 22 16:36:02 +0000 2019,RT @votevets: 1. John McCain was a war hero.\n...,0,17392,198,False,NaN,NaN,None,1. John McCain was a war hero.\n\n2. John McCa...,1.108447e+18,1.651334e+07,votevets,True,62408.0,158248.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
4,1109131633293037574,17200919,Michael Little,uzererr,Fri Mar 22 16:36:02 +0000 2019,RT @brithume: President Trump’s attacks on the...,0,1521,74,False,NaN,NaN,None,President Trump’s attacks on the late John McC...,1.109097e+18,1.120478e+08,brithume,True,9022.0,996715.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0

Add tweet ID

In [5]:
df_mccain_names = df_mccain.filter(['screen_name', 'retweet_screen_name', 'reply_to_screen_name', 'quoted_screen_name', 'tweet_id', 'rt_count', 'retweet_fav_count', 'quoted_fav_count', 'retweet_followers_count', 'retweet_is_verified', 'quoted_is_verified'], axis=1)

In [6]:
df_mccain_names.head()

,screen_name,retweet_screen_name,reply_to_screen_name,quoted_screen_name,tweet_id,rt_count,retweet_fav_count,quoted_fav_count,retweet_followers_count,retweet_is_verified,quoted_is_verified
0,WYATT251,thedilleyshow,None,NaN,1109131638112432129,107,299.0,NaN,8815.0,False,NaN
1,ellahoward271,LindseyGrahamSC,None,NaN,1109131636262744066,65,181.0,NaN,756904.0,True,NaN
2,janetlchatham,LouDobbs,None,NaN,1109131635742564352,158,366.0,NaN,1901004.0,True,NaN
3,dominikam42,votevets,None,NaN,1109131633603440640,17392,62408.0,NaN,158248.0,True,NaN
4,uzererr,brithume,None,NaN,1109131633293037574,1521,9022.0,NaN,996715.0,True,NaN

In [7]:
df_mccain_names.reply_to_screen_name.fillna(value=pd.np.nan, inplace=True)

In [8]:
df_mccain_names.head()

,screen_name,retweet_screen_name,reply_to_screen_name,quoted_screen_name,tweet_id,rt_count,retweet_fav_count,quoted_fav_count,retweet_followers_count,retweet_is_verified,quoted_is_verified
0,WYATT251,thedilleyshow,NaN,NaN,1109131638112432129,107,299.0,NaN,8815.0,False,NaN
1,ellahoward271,LindseyGrahamSC,NaN,NaN,1109131636262744066,65,181.0,NaN,756904.0,True,NaN
2,janetlchatham,LouDobbs,NaN,NaN,1109131635742564352,158,366.0,NaN,1901004.0,True,NaN
3,dominikam42,votevets,NaN,NaN,1109131633603440640,17392,62408.0,NaN,158248.0,True,NaN
4,uzererr,brithume,NaN,NaN,1109131633293037574,1521,9022.0,NaN,996715.0,True,NaN

In [9]:
print(df_mccain_names.shape)

## creating df's for replies, retweets, and quotes only. Can be added together later

#creating a df of retweets only
df_mccain_names_rts = df_mccain_names.dropna(axis=0, subset=['retweet_screen_name'])
print(df_mccain_names_rts.shape)

#creating a df of replies only
df_mccain_names_replies = df_mccain_names.dropna(axis=0, subset=['reply_to_screen_name'])
print(df_mccain_names_replies.shape)

#creating a df of quotes only
df_mccain_names_quotes = df_mccain_names.dropna(axis=0, subset=['quoted_screen_name'])
print(df_mccain_names_quotes.shape)

(1037841, 11)
(895858, 11)
(81418, 11)
(13121, 11)

Just a note - come back to the above if I need to add more information to my network data

Also - I'm just going to go with retweets first this time. Retweets more often imply someone is agreeing with what is being said, while a quote is often someone disagreeing

In [10]:
df_mccain_names_rts.sample(10)

,screen_name,retweet_screen_name,reply_to_screen_name,quoted_screen_name,tweet_id,rt_count,retweet_fav_count,quoted_fav_count,retweet_followers_count,retweet_is_verified,quoted_is_verified
2489,graybill_john,PeteButtigieg,NaN,NaN,1108535172322996229,25467,132766.0,NaN,430629.0,True,NaN
1441,scotte47145160,chuckwoolery,NaN,NaN,1108465875525554177,10851,33726.0,NaN,524068.0,True,NaN
2469,DianaV500,EdKrassen,NaN,NaN,1108360170080534528,1296,4517.0,NaN,900749.0,False,NaN
439,rmack2x,heyitsCarolyn,NaN,NaN,1107460610537779201,4410,4850.0,NaN,55406.0,False,NaN
1205,thoughtful1more,mitchellvii,NaN,NaN,1107973406874583040,347,1595.0,NaN,411401.0,True,NaN
326,ieatchalk,EdKrassen,NaN,NaN,1108002506238357506,4313,20967.0,NaN,900748.0,False,NaN
666,Bon__Mots,Robillard,NaN,NaN,1108738170101923840,1520,3171.0,NaN,19425.0,True,NaN
641,ProudHispanic04,goldengateblond,NaN,NaN,1108507316264026120,2061,14963.0,NaN,289348.0,True,NaN
3345,toschie,PostRoz,NaN,NaN,1107397491174064130,3425,8610.0,NaN,52054.0,True,NaN
1565,Shawn_Harder,peacelovinMimi,NaN,NaN,1107643980940865537,5,34.0,NaN,3695.0,False,NaN

In [11]:
# First creating undirected:
G_mccain_rt_und = nx.from_pandas_edgelist(df_mccain_names_rts, source='screen_name', target='retweet_screen_name', edge_attr=True, create_using=None)

# Second creating directed:
G_mccain_rt_dir = nx.from_pandas_edgelist(df_mccain_names_rts, source='screen_name', target='retweet_screen_name', edge_attr=True, create_using=nx.DiGraph())

In [12]:
print(nx.info(G_mccain_rt_und))
print(nx.info(G_mccain_rt_dir))

Name:
Type: Graph
Number of nodes: 291178
Number of edges: 812961
Average degree:   5.5839
Name:
Type: DiGraph
Number of nodes: 291178
Number of edges: 813158
Average in degree:   2.7926
Average out degree:   2.7926

In [13]:
# removing all self re-tweets
G_mccain_rt_und.remove_edges_from(G_mccain_rt_und.selfloop_edges())

In [14]:
print(nx.info(G_mccain_rt_und))
print(nx.info(G_mccain_rt_dir))

Name:
Type: Graph
Number of nodes: 291178
Number of edges: 811347
Average degree:   5.5729
Name:
Type: DiGraph
Number of nodes: 291178
Number of edges: 813158
Average in degree:   2.7926
Average out degree:   2.7926

That removed a few thousand - also, I am going to stick with undirected, because the next step undirects it anway

In [15]:
## The biggest component is way bigger than every other one, so we can just focus on that for the graph
G_mccain_rt_und_subgraphs = sorted(nx.connected_component_subgraphs(G_mccain_rt_und.to_undirected()), key=len, reverse=True)
print('Size of largest connected components:', [len(g) for g in G_mccain_rt_und_subgraphs[:20]])

Size of largest connected components: [288320, 33, 24, 16, 11, 9, 8, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 5]

In [16]:
G_mccain_rt_dir_subgraphs = sorted(nx.connected_component_subgraphs(G_mccain_rt_dir.to_undirected()), key=len, reverse=True)
print('Size of largest connected components:', [len(g) for g in G_mccain_rt_dir_subgraphs[:20]])

Size of largest connected components: [288320, 33, 24, 16, 11, 9, 8, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 5]

In [17]:
G_mccain_rt_und_final = G_mccain_rt_und_subgraphs[0]

In [18]:
G_mccain_rt_dir_final = G_mccain_rt_dir_subgraphs[0]

In [19]:
print(nx.info(G_mccain_rt_und_final))

Name:
Type: Graph
Number of nodes: 288320
Number of edges: 809902
Average degree:   5.6181

In [20]:
#Directed graph of strongest connected component for directed graph (USEING THIS FOR FINAL ANALYSIS, FEED INTO S FOR STRONGEST COMPONENT)
Gc_mccain_dir_rt = max(nx.strongly_connected_component_subgraphs(G_mccain_rt_dir), key=len)
print(nx.info(Gc_mccain_dir_rt))

Name:
Type: DiGraph
Number of nodes: 120
Number of edges: 483
Average in degree:   4.0250
Average out degree:   4.0250

In [28]:
# # Determine which community each user is in
# G_aoc_partition = community.best_partition(G_aoc_und_subgraphs[0].to_undirected())

In [29]:
# G_aoc_partition

In [30]:
# max(G_aoc_partition.values())

In [24]:
# # Find strongly connected components
# G_conn_comp = sorted(nx.strongly_connected_components(G_aoc_dir),key=len, reverse=True)
# print('Size of largest strongly connected components:', [len(g) for g in G_conn_comp[:20]])

Size of largest strongly connected components: [4001, 11, 8, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [27]:
# # Create graph of largest strongly connected component, this is just for the directed graph
# S = nx.subgraph(G_aoc_dir, G_conn_comp[0])

In [29]:
# #Calculating centrality measures on the sub graph object. All saved as a dict object
# pr = nx.pagerank(S)
# bt = nx.betweenness_centrality(S)
# cl = nx.closeness_centrality(S)

In [21]:
#Calculating centrality measures on the main graph object. All saved as a dict object
pr_all = nx.pagerank(G_mccain_rt_und_final)
# bt = nx.betweenness_centrality(S) ## this will never complete on a graph this size, will need to look into sampling

In [54]:
# bt = nx.betweenness_centrality(G_aoc_undir_final, k=10000) ## this will never complete on a graph this size, will need to look into sampling

For betweenness, try this:

https://stackoverflow.com/questions/32465503/networkx-never-finishes-calculating-betweenness-centrality-for-2-mil-nodes/32468942#32468942

In [55]:
# cl_all = nx.closeness_centrality(G_aoc_undir_final, k=myk)

In [22]:
## pickling each for safe keeping since it takes so long to run (roughly 20-30 minutes)

with open('/Users/robertpagano/src/metis_project_kojak/network_files/mccain/mccain_pagerank.pickle', 'wb') as to_write:
    pickle.dump(pr_all, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_pagerank_all.pickle', 'wb') as to_write:
#     pickle.dump(pr_all, to_write)
    
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_betweenness.pickle', 'wb') as to_write:
#     pickle.dump(bt, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_closeness.pickle', 'wb') as to_write:
#     pickle.dump(cl, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_maingraph_dir.pickle', 'wb') as to_write:
#     pickle.dump(S, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_maingraph_undir.pickle', 'wb') as to_write:
#     pickle.dump(G_aoc_undir_final, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_maingraph_partition.pickle', 'wb') as to_write:
#     pickle.dump(G_aoc_partition, to_write)

In [23]:
## saving down graph files to import into gephi. note that the undirected one is HUGE, let's see how they do...

nx.write_gexf(Gc_mccain_dir_rt, 'dir_subgraphs_fin_rt_mccain.gexf')
nx.write_gexf(G_mccain_rt_und_final, 'undir_fin_rt_mccain.gexf')

Here I am going to do the same, but with the "single" verified users. Meaning of the interactions, at least 1 needs to be verified

In [21]:
# with open('/Users/robertpagano/metis_data/project_5/final_verified_df.pickle', 'rb') as f:
#     df_aoc_verified = pickle.load(f)

In [22]:
# df_aoc_verified.head()

,tweet_id,user_id,display_name,screen_name,tweet_date,main_text,fav_count,rt_count,followers_count,is_verified,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,retweet_text,retweet_id,retweet_user_id,retweet_screen_name,retweet_is_verified,retweet_fav_count,retweet_followers_count,quoted_text,quoted_id,quoted_user_id,quoted_screen_name,quoted_is_verified,quoted_fav_count,is_retweet,is_quote
2333,1105325963825553408,59674605,Libertarian-In-Chief,ToddHagopian,Tue Mar 12 04:33:40 +0000 2019,@rakeshkamat @AOC Thankfully...they did not ha...,0,0,25641,True,1.105326e+18,1.628160e+07,rakeshkamat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2349,1105325949946605568,52644968,Brian Santa Maria,briansantamaria,Tue Mar 12 04:33:37 +0000 2019,@ashboi_ @tezzles @golovashkina @AOC In a popu...,1,0,4184,True,1.105319e+18,7.061243e+17,ashboi_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2361,1105325937942384642,14046504,Conor Friedersdorf,conor64,Tue Mar 12 04:33:34 +0000 2019,“Why is the relative patriotism of the two par...,6,0,55975,True,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True. It’s been GOP vs. the people of the Unit...,1.105286e+18,138203134.0,AOC,True,21607.0,0,1
3111,1105325041259032577,15358759,Las Vegas RJ,reviewjournal,Tue Mar 12 04:30:00 +0000 2019,"The freshman Democrat from New York, @AOC, has...",2,1,247123,True,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3246,1105324840985284608,59674605,Libertarian-In-Chief,ToddHagopian,Tue Mar 12 04:29:12 +0000 2019,"Every time I listen to @aoc speak, I try to re...",41,9,25641,True,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

In [23]:
# df_aoc_names_ver = df_aoc_verified.filter(['screen_name','retweet_screen_name', 'rt_count', 'retweet_fav_count', 'retweet_followers_count', 'retweet_is_verified'], axis=1)

In [24]:
# df_aoc_names_ver.head()

,screen_name,retweet_screen_name,rt_count,retweet_fav_count,retweet_followers_count,retweet_is_verified
2333,ToddHagopian,NaN,0,NaN,NaN,NaN
2349,briansantamaria,NaN,0,NaN,NaN,NaN
2361,conor64,NaN,0,NaN,NaN,NaN
3111,reviewjournal,NaN,1,NaN,NaN,NaN
3246,ToddHagopian,NaN,9,NaN,NaN,NaN

In [26]:
# df_aoc_names_ver = df_aoc_names_ver.isnull()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9217 entries, 2333 to 4020
Data columns (total 6 columns):
screen_name                9217 non-null object
retweet_screen_name        3889 non-null object
rt_count                   9217 non-null int64
retweet_fav_count          3889 non-null float64
retweet_followers_count    3889 non-null float64
retweet_is_verified        3889 non-null object
dtypes: float64(2), int64(1), object(3)
memory usage: 504.1+ KB

In [27]:
# print(df_aoc_names_ver.shape)
# df_aoc_names_ver = df_aoc_names_ver.dropna(axis=0, subset=['retweet_screen_name'])
# print(df_aoc_names_ver.shape)

(9217, 6)
(3889, 6)

In [28]:
# # First creating undirected:
# G_aoc_und_ver = nx.from_pandas_edgelist(df_aoc_names_ver, source='screen_name', target='retweet_screen_name', edge_attr=True, create_using=None)

# # Second creating directed:
# G_aoc_dir_ver = nx.from_pandas_edgelist(df_aoc_names_ver, source='screen_name', target='retweet_screen_name', edge_attr=True, create_using=nx.DiGraph())

In [29]:
# print(nx.info(G_aoc_und_ver))
# print(nx.info(G_aoc_dir_ver))

Name:
Type: Graph
Number of nodes: 3011
Number of edges: 3529
Average degree:   2.3441
Name:
Type: DiGraph
Number of nodes: 3011
Number of edges: 3543
Average in degree:   1.1767
Average out degree:   1.1767

In [30]:
# ## The biggest component is way bigger than every other one, so we can just focus on that for the graph
# G_aoc_und_subgraphs_ver = sorted(nx.connected_component_subgraphs(G_aoc_und_ver.to_undirected()), key=len, reverse=True)
# print('Size of largest connected components:', [len(g) for g in G_aoc_und_subgraphs_ver[:20]])

Size of largest connected components: [2202, 24, 15, 13, 10, 9, 6, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4]

In [31]:
# G_aoc_undir_final_ver = G_aoc_und_subgraphs_ver[0]

In [32]:
# nx.write_gexf(G_aoc_undir_final_ver, 'undir_fin_ver.gexf')