In [1]:
import networkx as nx

import pandas as pd
import numpy as np

import pickle

import community

In [2]:
pd.set_option('display.max_columns', 500)

In [3]:
with open('/Users/robertpagano/metis_data/project_5/final_raw_marvel_df.pickle', 'rb') as f:
    df_marvel = pickle.load(f)

In [4]:
df_marvel.head()

,tweet_id,user_id,display_name,screen_name,tweet_date,main_text,fav_count,rt_count,followers_count,is_verified,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,retweet_text,retweet_id,retweet_user_id,retweet_screen_name,retweet_is_verified,retweet_fav_count,retweet_followers_count,quoted_text,quoted_id,quoted_user_id,quoted_screen_name,quoted_is_verified,quoted_fav_count,is_retweet,is_quote
0,1107088444658978816,442928354,Erica Miller,EricaFMiller,Sun Mar 17 01:17:08 +0000 2019,RT @Raulc_52: Intro to Captain Marvel\nMe: htt...,0,5,128,False,NaN,NaN,None,Intro to Captain Marvel\nMe: https://t.co/WMJT...,1.107028e+18,2.344318e+09,Raulc_52,False,13.0,407.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
1,1107088442356367360,408092583,Annie Rachel,Annferddd,Sun Mar 17 01:17:08 +0000 2019,RT @gwilymst: captain marvel without context ...,0,32858,411,False,NaN,NaN,None,captain marvel without context https://t.co/F...,1.106192e+18,1.042657e+18,gwilymst,False,70766.0,368.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
2,1107088441588830209,902039904099684352,ùô†ùôÆùôßùôñ ‚ô°,cptkyra,Sun Mar 17 01:17:07 +0000 2019,RT @lalisamcu: the gays when the scene cut to ...,0,26,147,False,NaN,NaN,None,the gays when the scene cut to brie larson rid...,1.105913e+18,9.735315e+17,lalisamcu,False,97.0,112.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
3,1107088439382429696,985172108547309569,Î†àÎèåÏÉ®,chisakaoo,Sun Mar 17 01:17:07 +0000 2019,RT @cyanwhisky: #AvengersEndgame #CaptainMarve...,0,13712,60,False,NaN,NaN,None,#AvengersEndgame #CaptainMarvel OK I'm ready f...,1.106903e+18,1.966503e+08,cyanwhisky,False,31450.0,26699.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
4,1107088438703128576,2864913304,dirty diana,dollyweep,Sun Mar 17 01:17:07 +0000 2019,RT @gwilymst: captain marvel without context ...,0,32858,141,False,NaN,NaN,None,captain marvel without context https://t.co/F...,1.106192e+18,1.042657e+18,gwilymst,False,70766.0,368.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0

Add tweet ID

In [5]:
df_marvel_names = df_marvel.filter(['screen_name', 'retweet_screen_name', 'reply_to_screen_name', 'quoted_screen_name', 'tweet_id', 'rt_count', 'retweet_fav_count', 'quoted_fav_count', 'retweet_followers_count', 'retweet_is_verified', 'quoted_is_verified'], axis=1)

In [6]:
df_marvel_names.head()

,screen_name,retweet_screen_name,reply_to_screen_name,quoted_screen_name,tweet_id,rt_count,retweet_fav_count,quoted_fav_count,retweet_followers_count,retweet_is_verified,quoted_is_verified
0,EricaFMiller,Raulc_52,None,NaN,1107088444658978816,5,13.0,NaN,407.0,False,NaN
1,Annferddd,gwilymst,None,NaN,1107088442356367360,32858,70766.0,NaN,368.0,False,NaN
2,cptkyra,lalisamcu,None,NaN,1107088441588830209,26,97.0,NaN,112.0,False,NaN
3,chisakaoo,cyanwhisky,None,NaN,1107088439382429696,13712,31450.0,NaN,26699.0,False,NaN
4,dollyweep,gwilymst,None,NaN,1107088438703128576,32858,70766.0,NaN,368.0,False,NaN

In [7]:
df_marvel_names.reply_to_screen_name.fillna(value=pd.np.nan, inplace=True)

In [8]:
df_marvel_names.head()

,screen_name,retweet_screen_name,reply_to_screen_name,quoted_screen_name,tweet_id,rt_count,retweet_fav_count,quoted_fav_count,retweet_followers_count,retweet_is_verified,quoted_is_verified
0,EricaFMiller,Raulc_52,NaN,NaN,1107088444658978816,5,13.0,NaN,407.0,False,NaN
1,Annferddd,gwilymst,NaN,NaN,1107088442356367360,32858,70766.0,NaN,368.0,False,NaN
2,cptkyra,lalisamcu,NaN,NaN,1107088441588830209,26,97.0,NaN,112.0,False,NaN
3,chisakaoo,cyanwhisky,NaN,NaN,1107088439382429696,13712,31450.0,NaN,26699.0,False,NaN
4,dollyweep,gwilymst,NaN,NaN,1107088438703128576,32858,70766.0,NaN,368.0,False,NaN

In [9]:
print(df_marvel_names.shape)

## creating df's for replies, retweets, and quotes only. Can be added together later

#creating a df of retweets only
df_marvel_names_rts = df_marvel_names.dropna(axis=0, subset=['retweet_screen_name'])
print(df_marvel_names_rts.shape)

#creating a df of replies only
df_marvel_names_replies = df_marvel_names.dropna(axis=0, subset=['reply_to_screen_name'])
print(df_marvel_names_replies.shape)

#creating a df of quotes only
df_marvel_names_quotes = df_marvel_names.dropna(axis=0, subset=['quoted_screen_name'])
print(df_marvel_names_quotes.shape)

(1779794, 11)
(1155778, 11)
(156116, 11)
(25993, 11)

Just a note - come back to the above if I need to add more information to my network data

Also - I'm just going to go with retweets first this time. Retweets more often imply someone is agreeing with what is being said, while a quote is often someone disagreeing

In [10]:
df_marvel_names_rts.sample(10)

,screen_name,retweet_screen_name,reply_to_screen_name,quoted_screen_name,tweet_id,rt_count,retweet_fav_count,quoted_fav_count,retweet_followers_count,retweet_is_verified,quoted_is_verified
3724,AndrewTomlinsky,ChrisEvans,NaN,NaN,1105146274720866304,23582,191746.0,NaN,10615164.0,True,NaN
1309,Sirloinofice1,Sleestak,NaN,NaN,1104455092621766656,1,4.0,NaN,1305.0,False,NaN
2908,RandomLittleImp,OriginalFunko,NaN,NaN,1104895564116713472,14643,6241.0,NaN,961466.0,True,NaN
1577,ChasDuncanII,nytimes,NaN,NaN,1104909205448937472,220,1286.0,NaN,43047680.0,True,NaN
2119,DamionDamaske,JennKaytin,NaN,NaN,1105420570118676482,2176,10704.0,NaN,17492.0,True,NaN
101,Nabilalailatul,leepace,NaN,NaN,1104356468290019330,1228,10643.0,NaN,265443.0,True,NaN
3209,all4notin,BreakingViews4u,NaN,NaN,1103955400032837632,3,5.0,NaN,21631.0,False,NaN
2898,nosleeves17,MattTurnerOF,NaN,NaN,1105266576855650305,1,2.0,NaN,726.0,False,NaN
1790,blairbendler,BBW_BFF,NaN,NaN,1105900986361622529,6447,18544.0,NaN,54497.0,True,NaN
2509,TheoBrando420,EmilHofilena,NaN,NaN,1105009973543591936,14467,43284.0,NaN,2378.0,False,NaN

In [17]:
# First creating undirected:
G_marvel_rt_und = nx.from_pandas_edgelist(df_marvel_names_rts, source='screen_name', target='retweet_screen_name', edge_attr=True, create_using=None)

# Second creating directed:
G_marvel_rt_dir = nx.from_pandas_edgelist(df_marvel_names_rts, source='screen_name', target='retweet_screen_name', edge_attr=True, create_using=nx.DiGraph())

In [18]:
print(nx.info(G_marvel_rt_und))
print(nx.info(G_marvel_rt_dir))

Name:
Type: Graph
Number of nodes: 569380
Number of edges: 1005000
Average degree:   3.5302
Name:
Type: DiGraph
Number of nodes: 569380
Number of edges: 1006167
Average in degree:   1.7671
Average out degree:   1.7671

In [19]:
# removing all self re-tweets
G_marvel_rt_und.remove_edges_from(G_marvel_rt_und.selfloop_edges())

In [20]:
print(nx.info(G_marvel_rt_und))
print(nx.info(G_marvel_rt_dir))

Name:
Type: Graph
Number of nodes: 569380
Number of edges: 1002440
Average degree:   3.5212
Name:
Type: DiGraph
Number of nodes: 569380
Number of edges: 1006167
Average in degree:   1.7671
Average out degree:   1.7671

That removed a few thousand - also, I am going to stick with undirected, because the next step undirects it anway

In [22]:
## The biggest component is way bigger than every other one, so we can just focus on that for the graph
G_marvel_rt_und_subgraphs = sorted(nx.connected_component_subgraphs(G_marvel_rt_und.to_undirected()), key=len, reverse=True)
print('Size of largest connected components:', [len(g) for g in G_marvel_rt_und_subgraphs[:20]])

Size of largest connected components: [536602, 151, 103, 88, 51, 46, 45, 25, 24, 23, 22, 21, 21, 21, 20, 18, 18, 18, 17, 17]

In [21]:
G_marvel_rt_dir_subgraphs = sorted(nx.connected_component_subgraphs(G_marvel_rt_dir.to_undirected()), key=len, reverse=True)
print('Size of largest connected components:', [len(g) for g in G_marvel_rt_dir_subgraphs[:20]])

Size of largest connected components: [536602, 151, 103, 88, 51, 46, 45, 25, 24, 23, 22, 21, 21, 21, 20, 18, 18, 18, 17, 17]

In [23]:
G_marvel_rt_und_final = G_marvel_rt_und_subgraphs[0]

In [24]:
G_marvel_rt_dir_final = G_marvel_rt_dir_subgraphs[0]

In [25]:
print(nx.info(G_marvel_rt_und_final))

Name:
Type: Graph
Number of nodes: 536602
Number of edges: 983188
Average degree:   3.6645

In [26]:
#Directed graph of strongest connected component for directed graph (USEING THIS FOR FINAL ANALYSIS, FEED INTO S FOR STRONGEST COMPONENT)
Gc_marvel_dir_rt = max(nx.strongly_connected_component_subgraphs(G_marvel_rt_dir), key=len)
print(nx.info(Gc_marvel_dir_rt))

Name:
Type: DiGraph
Number of nodes: 2478
Number of edges: 15713
Average in degree:   6.3410
Average out degree:   6.3410

In [28]:
# # Determine which community each user is in
# G_aoc_partition = community.best_partition(G_aoc_und_subgraphs[0].to_undirected())

In [29]:
# G_aoc_partition

In [30]:
# max(G_aoc_partition.values())

In [24]:
# # Find strongly connected components
# G_conn_comp = sorted(nx.strongly_connected_components(G_aoc_dir),key=len, reverse=True)
# print('Size of largest strongly connected components:', [len(g) for g in G_conn_comp[:20]])

Size of largest strongly connected components: [4001, 11, 8, 5, 5, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [27]:
# # Create graph of largest strongly connected component, this is just for the directed graph
# S = nx.subgraph(G_aoc_dir, G_conn_comp[0])

In [29]:
# #Calculating centrality measures on the sub graph object. All saved as a dict object
# pr = nx.pagerank(S)
# bt = nx.betweenness_centrality(S)
# cl = nx.closeness_centrality(S)

In [27]:
#Calculating centrality measures on the main graph object. All saved as a dict object
pr_all = nx.pagerank(G_marvel_rt_und_final)
# bt = nx.betweenness_centrality(S) ## this will never complete on a graph this size, will need to look into sampling

In [54]:
# bt = nx.betweenness_centrality(G_aoc_undir_final, k=10000) ## this will never complete on a graph this size, will need to look into sampling

For betweenness, try this:

https://stackoverflow.com/questions/32465503/networkx-never-finishes-calculating-betweenness-centrality-for-2-mil-nodes/32468942#32468942

In [55]:
# cl_all = nx.closeness_centrality(G_aoc_undir_final, k=myk)

In [28]:
## pickling each for safe keeping since it takes so long to run (roughly 20-30 minutes)

with open('/Users/robertpagano/src/metis_project_kojak/network_files/marvel/marvel_pagerank.pickle', 'wb') as to_write:
    pickle.dump(pr_all, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_pagerank_all.pickle', 'wb') as to_write:
#     pickle.dump(pr_all, to_write)
    
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_betweenness.pickle', 'wb') as to_write:
#     pickle.dump(bt, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_closeness.pickle', 'wb') as to_write:
#     pickle.dump(cl, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_maingraph_dir.pickle', 'wb') as to_write:
#     pickle.dump(S, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_maingraph_undir.pickle', 'wb') as to_write:
#     pickle.dump(G_aoc_undir_final, to_write)
    
# with open('/Users/robertpagano/src/metis_project_kojak/network_files/aoc/aoc_maingraph_partition.pickle', 'wb') as to_write:
#     pickle.dump(G_aoc_partition, to_write)

In [29]:
## saving down graph files to import into gephi. note that the undirected one is HUGE, let's see how they do...

nx.write_gexf(Gc_marvel_dir_rt, 'dir_subgraphs_fin_rt_marvel.gexf')
nx.write_gexf(G_marvel_rt_und_final, 'undir_fin_rt_marvel.gexf')

Here I am going to do the same, but with the "single" verified users. Meaning of the interactions, at least 1 needs to be verified

In [21]:
# with open('/Users/robertpagano/metis_data/project_5/final_verified_df.pickle', 'rb') as f:
#     df_aoc_verified = pickle.load(f)

In [22]:
# df_aoc_verified.head()

,tweet_id,user_id,display_name,screen_name,tweet_date,main_text,fav_count,rt_count,followers_count,is_verified,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,retweet_text,retweet_id,retweet_user_id,retweet_screen_name,retweet_is_verified,retweet_fav_count,retweet_followers_count,quoted_text,quoted_id,quoted_user_id,quoted_screen_name,quoted_is_verified,quoted_fav_count,is_retweet,is_quote
2333,1105325963825553408,59674605,Libertarian-In-Chief,ToddHagopian,Tue Mar 12 04:33:40 +0000 2019,@rakeshkamat @AOC Thankfully...they did not ha...,0,0,25641,True,1.105326e+18,1.628160e+07,rakeshkamat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2349,1105325949946605568,52644968,Brian Santa Maria,briansantamaria,Tue Mar 12 04:33:37 +0000 2019,@ashboi_ @tezzles @golovashkina @AOC In a popu...,1,0,4184,True,1.105319e+18,7.061243e+17,ashboi_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2361,1105325937942384642,14046504,Conor Friedersdorf,conor64,Tue Mar 12 04:33:34 +0000 2019,‚ÄúWhy is the relative patriotism of the two par...,6,0,55975,True,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True. It‚Äôs been GOP vs. the people of the Unit...,1.105286e+18,138203134.0,AOC,True,21607.0,0,1
3111,1105325041259032577,15358759,Las Vegas RJ,reviewjournal,Tue Mar 12 04:30:00 +0000 2019,"The freshman Democrat from New York, @AOC, has...",2,1,247123,True,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3246,1105324840985284608,59674605,Libertarian-In-Chief,ToddHagopian,Tue Mar 12 04:29:12 +0000 2019,"Every time I listen to @aoc speak, I try to re...",41,9,25641,True,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

In [23]:
# df_aoc_names_ver = df_aoc_verified.filter(['screen_name','retweet_screen_name', 'rt_count', 'retweet_fav_count', 'retweet_followers_count', 'retweet_is_verified'], axis=1)

In [24]:
# df_aoc_names_ver.head()

,screen_name,retweet_screen_name,rt_count,retweet_fav_count,retweet_followers_count,retweet_is_verified
2333,ToddHagopian,NaN,0,NaN,NaN,NaN
2349,briansantamaria,NaN,0,NaN,NaN,NaN
2361,conor64,NaN,0,NaN,NaN,NaN
3111,reviewjournal,NaN,1,NaN,NaN,NaN
3246,ToddHagopian,NaN,9,NaN,NaN,NaN

In [26]:
# df_aoc_names_ver = df_aoc_names_ver.isnull()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9217 entries, 2333 to 4020
Data columns (total 6 columns):
screen_name                9217 non-null object
retweet_screen_name        3889 non-null object
rt_count                   9217 non-null int64
retweet_fav_count          3889 non-null float64
retweet_followers_count    3889 non-null float64
retweet_is_verified        3889 non-null object
dtypes: float64(2), int64(1), object(3)
memory usage: 504.1+ KB

In [27]:
# print(df_aoc_names_ver.shape)
# df_aoc_names_ver = df_aoc_names_ver.dropna(axis=0, subset=['retweet_screen_name'])
# print(df_aoc_names_ver.shape)

(9217, 6)
(3889, 6)

In [28]:
# # First creating undirected:
# G_aoc_und_ver = nx.from_pandas_edgelist(df_aoc_names_ver, source='screen_name', target='retweet_screen_name', edge_attr=True, create_using=None)

# # Second creating directed:
# G_aoc_dir_ver = nx.from_pandas_edgelist(df_aoc_names_ver, source='screen_name', target='retweet_screen_name', edge_attr=True, create_using=nx.DiGraph())

In [29]:
# print(nx.info(G_aoc_und_ver))
# print(nx.info(G_aoc_dir_ver))

Name:
Type: Graph
Number of nodes: 3011
Number of edges: 3529
Average degree:   2.3441
Name:
Type: DiGraph
Number of nodes: 3011
Number of edges: 3543
Average in degree:   1.1767
Average out degree:   1.1767

In [30]:
# ## The biggest component is way bigger than every other one, so we can just focus on that for the graph
# G_aoc_und_subgraphs_ver = sorted(nx.connected_component_subgraphs(G_aoc_und_ver.to_undirected()), key=len, reverse=True)
# print('Size of largest connected components:', [len(g) for g in G_aoc_und_subgraphs_ver[:20]])

Size of largest connected components: [2202, 24, 15, 13, 10, 9, 6, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4]

In [31]:
# G_aoc_undir_final_ver = G_aoc_und_subgraphs_ver[0]

In [32]:
# nx.write_gexf(G_aoc_undir_final_ver, 'undir_fin_ver.gexf')