In [1]:
import tweepy, sys, os, logging, json

import pandas as pd
import numpy as np

import pickle

from tweet_clean import deefify2

In [2]:
pd.set_option('display.max_columns', 500)

Below I am loading json files for each of my 391 json files. Once I am done with that:
 - munge all using deefify2
 - merge all files
 - remove any duplicate tweet IDs
 
Then that's my final dataframe with all data. From there I can select the data I want to run my graph

In [3]:
def create_df(json_filename):
    # inputs a json file, converts to json object, then runs the data clean function
    # will need to loop through all json files, and then merge the dataframes
    with open(json_filename) as json_file:
        tweets = json.load(json_file)
    return deefify2(tweets)

Creating a dataframe of each individual data file, then I will merge with one long concat call

In [4]:
df_0=create_df('tweets0.json')
df_1=create_df('tweets1.json')
df_2=create_df('tweets2.json')
df_3=create_df('tweets3.json')
df_4=create_df('tweets4.json')
df_5=create_df('tweets5.json')
df_6=create_df('tweets6.json')
df_7=create_df('tweets7.json')
df_8=create_df('tweets8.json')
df_9=create_df('tweets9.json')
df_10=create_df('tweets10.json')
df_11=create_df('tweets11.json')
df_12=create_df('tweets12.json')
df_13=create_df('tweets13.json')
df_14=create_df('tweets14.json')
df_15=create_df('tweets15.json')
df_16=create_df('tweets16.json')
df_17=create_df('tweets17.json')
df_18=create_df('tweets18.json')
df_19=create_df('tweets19.json')
df_20=create_df('tweets20.json')
df_21=create_df('tweets21.json')
df_22=create_df('tweets22.json')
df_23=create_df('tweets23.json')
df_24=create_df('tweets24.json')
df_25=create_df('tweets25.json')
df_26=create_df('tweets26.json')
df_27=create_df('tweets27.json')
df_28=create_df('tweets28.json')
df_29=create_df('tweets29.json')
df_30=create_df('tweets30.json')
df_31=create_df('tweets31.json')
df_32=create_df('tweets32.json')
df_33=create_df('tweets33.json')
df_34=create_df('tweets34.json')
df_35=create_df('tweets35.json')
df_36=create_df('tweets36.json')
df_37=create_df('tweets37.json')
df_38=create_df('tweets38.json')
df_39=create_df('tweets39.json')
df_40=create_df('tweets40.json')
df_41=create_df('tweets41.json')
df_42=create_df('tweets42.json')
df_43=create_df('tweets43.json')
df_44=create_df('tweets44.json')
df_45=create_df('tweets45.json')
df_46=create_df('tweets46.json')
df_47=create_df('tweets47.json')
df_48=create_df('tweets48.json')
df_49=create_df('tweets49.json')
df_50=create_df('tweets50.json')
df_51=create_df('tweets51.json')
df_52=create_df('tweets52.json')
df_53=create_df('tweets53.json')
df_54=create_df('tweets54.json')
df_55=create_df('tweets55.json')
df_56=create_df('tweets56.json')
df_57=create_df('tweets57.json')
df_58=create_df('tweets58.json')
df_59=create_df('tweets59.json')
df_60=create_df('tweets60.json')
df_61=create_df('tweets61.json')
df_62=create_df('tweets62.json')
df_63=create_df('tweets63.json')
df_64=create_df('tweets64.json')
df_65=create_df('tweets65.json')
df_66=create_df('tweets66.json')
df_67=create_df('tweets67.json')
df_68=create_df('tweets68.json')
df_69=create_df('tweets69.json')
df_70=create_df('tweets70.json')
df_71=create_df('tweets71.json')
df_72=create_df('tweets72.json')
df_73=create_df('tweets73.json')
df_74=create_df('tweets74.json')
df_75=create_df('tweets75.json')
df_76=create_df('tweets76.json')
df_77=create_df('tweets77.json')
df_78=create_df('tweets78.json')
df_79=create_df('tweets79.json')
df_80=create_df('tweets80.json')
df_81=create_df('tweets81.json')
df_82=create_df('tweets82.json')
df_83=create_df('tweets83.json')
df_84=create_df('tweets84.json')
df_85=create_df('tweets85.json')
df_86=create_df('tweets86.json')
df_87=create_df('tweets87.json')
df_88=create_df('tweets88.json')
df_89=create_df('tweets89.json')
df_90=create_df('tweets90.json')
df_91=create_df('tweets91.json')
df_92=create_df('tweets92.json')
df_93=create_df('tweets93.json')
df_94=create_df('tweets94.json')
df_95=create_df('tweets95.json')
df_96=create_df('tweets96.json')
df_97=create_df('tweets97.json')
df_98=create_df('tweets98.json')
df_99=create_df('tweets99.json')
df_100=create_df('tweets100.json')
df_101=create_df('tweets101.json')
df_102=create_df('tweets102.json')
df_103=create_df('tweets103.json')
df_104=create_df('tweets104.json')
df_105=create_df('tweets105.json')
df_106=create_df('tweets106.json')
df_107=create_df('tweets107.json')
df_108=create_df('tweets108.json')
df_109=create_df('tweets109.json')
df_110=create_df('tweets110.json')
df_111=create_df('tweets111.json')
df_112=create_df('tweets112.json')
df_113=create_df('tweets113.json')
df_114=create_df('tweets114.json')
df_115=create_df('tweets115.json')
df_116=create_df('tweets116.json')
df_117=create_df('tweets117.json')
df_118=create_df('tweets118.json')
df_119=create_df('tweets119.json')
df_120=create_df('tweets120.json')
df_121=create_df('tweets121.json')
df_122=create_df('tweets122.json')
df_123=create_df('tweets123.json')
df_124=create_df('tweets124.json')
df_125=create_df('tweets125.json')

In [5]:
df_125.head()

,tweet_id,user_id,display_name,screen_name,tweet_date,main_text,fav_count,rt_count,followers_count,is_verified,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,retweet_text,retweet_id,retweet_user_id,retweet_screen_name,retweet_is_verified,retweet_fav_count,retweet_followers_count,quoted_text,quoted_id,quoted_user_id,quoted_screen_name,quoted_is_verified,quoted_fav_count,is_retweet,is_quote
0,1105542476176216064,1210098278,Christine Caston,CastonChris,Tue Mar 12 18:54:00 +0000 2019,"RT @JuddLegum: Tucker Carlson said ""white men""...",0,9275,1953,False,NaN,NaN,None,"Tucker Carlson said ""white men"" deserve credit...",1.105268e+18,1.546470e+07,JuddLegum,True,21014.0,337546.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
1,1105542472258736128,91472402,melita bommarito,MelitaBommarito,Tue Mar 12 18:54:00 +0000 2019,RT @Uncle_Jimbo: #TuckerCarlson planted the fl...,0,6385,4504,False,NaN,NaN,None,#TuckerCarlson planted the flag &amp; announce...,1.105267e+18,1.575758e+07,Uncle_Jimbo,True,18365.0,62123.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
2,1105542461034659840,294328909,Chris,Talon269,Tue Mar 12 18:53:57 +0000 2019,RT @tedlieu: I wondered if Tucker Carlson was ...,0,2892,1625,False,NaN,NaN,None,I wondered if Tucker Carlson was merely acting...,1.105309e+18,2.105926e+07,tedlieu,True,9243.0,972827.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
3,1105542436464422912,10931862,beckinor,beckinor,Tue Mar 12 18:53:51 +0000 2019,RT @Amy_Siskind: That moment you realize Tucke...,0,365,114,False,NaN,NaN,None,That moment you realize Tucker Carlson’s comme...,1.105529e+18,1.597670e+07,Amy_Siskind,True,868.0,349064.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
4,1105542432446472192,805458926,Tex Irvin,TexIrvin,Tue Mar 12 18:53:50 +0000 2019,RT @RealDCWhispers: Will You Support Tucker Ca...,0,4,1005,False,NaN,NaN,None,Will You Support Tucker Carlson As Far Left De...,1.105248e+18,8.304515e+17,RealDCWhispers,False,6.0,1499.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0

In [6]:
def concat_dfs(num):
    x = 0
    df_list = []
    while x < num:
        df_list.append(f'df_{x}')
        x +=1
    return df_list

In [7]:
df_list = [df_0,
 df_1,
 df_2,
 df_3,
 df_4,
 df_5,
 df_6,
 df_7,
 df_8,
 df_9,
 df_10,
 df_11,
 df_12,
 df_13,
 df_14,
 df_15,
 df_16,
 df_17,
 df_18,
 df_19,
 df_20,
 df_21,
 df_22,
 df_23,
 df_24,
 df_25,
 df_26,
 df_27,
 df_28,
 df_29,
 df_30,
 df_31,
 df_32,
 df_33,
 df_34,
 df_35,
 df_36,
 df_37,
 df_38,
 df_39,
 df_40,
 df_41,
 df_42,
 df_43,
 df_44,
 df_45,
 df_46,
 df_47,
 df_48,
 df_49,
 df_50,
 df_51,
 df_52,
 df_53,
 df_54,
 df_55,
 df_56,
 df_57,
 df_58,
 df_59,
 df_60,
 df_61,
 df_62,
 df_63,
 df_64,
 df_65,
 df_66,
 df_67,
 df_68,
 df_69,
 df_70,
 df_71,
 df_72,
 df_73,
 df_74,
 df_75,
 df_76,
 df_77,
 df_78,
 df_79,
 df_80,
 df_81,
 df_82,
 df_83,
 df_84,
 df_85,
 df_86,
 df_87,
 df_88,
 df_89,
 df_90,
 df_91,
 df_92,
 df_93,
 df_94,
 df_95,
 df_96,
 df_97,
 df_98,
 df_99,
 df_100,
 df_101,
 df_102,
 df_103,
 df_104,
 df_105,
 df_106,
 df_107,
 df_108,
 df_109,
 df_110,
 df_111,
 df_112,
 df_113,
 df_114,
 df_115,
 df_116,
 df_117,
 df_118,
 df_119,
 df_120,
 df_121,
 df_122,
 df_123,
 df_124,
 df_125]

In [8]:
final_tucker_df = pd.concat(df_list)

In [9]:
final_tucker_df.shape

(509602, 28)

In [10]:
final_tucker_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 509602 entries, 0 to 3677
Data columns (total 28 columns):
tweet_id                   509602 non-null int64
user_id                    509602 non-null int64
display_name               509602 non-null object
screen_name                509602 non-null object
tweet_date                 509602 non-null object
main_text                  509602 non-null object
fav_count                  509602 non-null int64
rt_count                   509602 non-null int64
followers_count            509602 non-null int64
is_verified                509602 non-null bool
reply_to_tweet_id          89684 non-null float64
reply_to_user_id           104241 non-null float64
reply_to_screen_name       104241 non-null object
retweet_text               359957 non-null object
retweet_id                 359957 non-null float64
retweet_user_id            359957 non-null float64
retweet_screen_name        359957 non-null object
retweet_is_verified        359957 non-null object
retweet_fav_count          359957 non-null float64
retweet_followers_count    359957 non-null float64
quoted_text                13190 non-null object
quoted_id                  13190 non-null float64
quoted_user_id             13190 non-null float64
quoted_screen_name         13190 non-null object
quoted_is_verified         13190 non-null object
quoted_fav_count           13190 non-null float64
is_retweet                 509602 non-null int64
is_quote                   509602 non-null int64
dtypes: bool(1), float64(9), int64(7), object(11)
memory usage: 109.3+ MB

In [13]:
final_tucker_df.head()

,tweet_id,user_id,display_name,screen_name,tweet_date,main_text,fav_count,rt_count,followers_count,is_verified,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,retweet_text,retweet_id,retweet_user_id,retweet_screen_name,retweet_is_verified,retweet_fav_count,retweet_followers_count,quoted_text,quoted_id,quoted_user_id,quoted_screen_name,quoted_is_verified,quoted_fav_count,is_retweet,is_quote
0,1108898530125668352,819975326663114754,Sheryl,Sheryl2100,Fri Mar 22 01:09:46 +0000 2019,RT @JuddLegum: .@progressive quietly stopped a...,0,535,220,False,NaN,NaN,None,.@progressive quietly stopped advertising on T...,1.108893e+18,15464697.0,JuddLegum,True,1035.0,337485.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
1,1108898518821933056,1908173622,❌Yoo Hoo ✝️ Ecc 10:2 🇺🇸 Pro 15:3,Watchman4the1,Fri Mar 22 01:09:43 +0000 2019,@TuckerCarlson &amp; @seanhannity&gt;&gt;&gt; ...,0,0,3440,False,NaN,22703645.0,TuckerCarlson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,1108898513805627397,578116913,Samuel Adams,jgrissom63,Fri Mar 22 01:09:42 +0000 2019,@marklevinshow Sorry but like thousands others...,0,0,2568,False,1.108851e+18,38495835.0,marklevinshow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,1108898512798957568,3298861641,राधिका,nakiarn25,Fri Mar 22 01:09:42 +0000 2019,RT @JuddLegum: .@progressive quietly stopped a...,0,535,62,False,NaN,NaN,None,.@progressive quietly stopped advertising on T...,1.108893e+18,15464697.0,JuddLegum,True,1035.0,337485.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
4,1108898512173977605,2425284969,shaivon Cherry,sherryw329,Fri Mar 22 01:09:42 +0000 2019,RT @JuddLegum: .@progressive quietly stopped a...,0,535,492,False,NaN,NaN,None,.@progressive quietly stopped advertising on T...,1.108893e+18,15464697.0,JuddLegum,True,1035.0,337485.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0

In [12]:
# Out of the 509k million tweets, 4704 are from verified users
(final_tucker_df['is_verified'] == True).sum()

4704

In [14]:
# Out of the 509k million tweets, 359957 are retweets
(final_tucker_df['is_retweet'] == 1).sum()

359957

In [16]:
# Out of the 509k million tweets, 13190 are quotes
(final_tucker_df['is_quote'] == 1).sum()

13190

Now I will try to de-duplicate by tweet ID, to make sure I don't have duplicate rows

In [17]:
# All tweets in the dataset are unique
final_tucker_df['tweet_id'].nunique()

509602

In [18]:
# There are 214055 unique users that have tweeted
final_tucker_df['user_id'].nunique()

214055

Pickling my final raw df for safe keeping

In [20]:
with open('/Users/robertpagano/metis_data/project_5/final_raw_tucker_df.pickle', 'wb') as to_write:
    pickle.dump(final_tucker_df, to_write)

I want to look at users who 100% retweet, and check how many there are for various counts. so for example, if a user has say 50 retweets in the last week, and no original tweets, this person is likely either a bot, or someone that no one else is ever really connecting to. Not relevant to my analysis

In [21]:
df_tucker_verified = final_tucker_df[final_tucker_df['is_verified'] == True]

In [22]:
df_tucker_verified.shape

(4704, 28)

In [23]:
df_tucker_verified.nunique()

tweet_id                   4704
user_id                    1955
display_name               1954
screen_name                1955
tweet_date                 4657
main_text                  3333
fav_count                   525
rt_count                    444
followers_count            2850
is_verified                   1
reply_to_tweet_id           593
reply_to_user_id            438
reply_to_screen_name        438
retweet_text                957
retweet_id                  962
retweet_user_id             626
retweet_screen_name         626
retweet_is_verified           2
retweet_fav_count           596
retweet_followers_count    1031
quoted_text                 202
quoted_id                   202
quoted_user_id              153
quoted_screen_name          153
quoted_is_verified            2
quoted_fav_count            177
is_retweet                    2
is_quote                      2
dtype: int64

In [24]:
with open('/Users/robertpagano/metis_data/project_5/df_tucker_verified.pickle', 'wb') as to_write:
    pickle.dump(df_tucker_verified, to_write)