In [1]:
import tweepy, sys, os, logging, json

import pandas as pd
import numpy as np

import pickle

from tweet_clean import deefify2

In [2]:
pd.set_option('display.max_columns', 500)

Below I am loading json files for each of my 391 json files. Once I am done with that:
 - munge all using deefify2
 - merge all files
 - remove any duplicate tweet IDs
 
Then that's my final dataframe with all data. From there I can select the data I want to run my graph

In [3]:
def create_df(json_filename):
    # inputs a json file, converts to json object, then runs the data clean function
    # will need to loop through all json files, and then merge the dataframes
    with open(json_filename) as json_file:
        tweets = json.load(json_file)
    return deefify2(tweets)

Creating a dataframe of each individual data file, then I will merge with one long concat call

In [4]:
df_0=create_df('tweets0.json')
df_1=create_df('tweets1.json')
df_2=create_df('tweets2.json')
df_3=create_df('tweets3.json')
df_4=create_df('tweets4.json')
df_5=create_df('tweets5.json')
df_6=create_df('tweets6.json')
df_7=create_df('tweets7.json')
df_8=create_df('tweets8.json')
df_9=create_df('tweets9.json')
df_10=create_df('tweets10.json')
df_11=create_df('tweets11.json')
df_12=create_df('tweets12.json')
df_13=create_df('tweets13.json')
df_14=create_df('tweets14.json')
df_15=create_df('tweets15.json')
df_16=create_df('tweets16.json')
df_17=create_df('tweets17.json')
df_18=create_df('tweets18.json')
df_19=create_df('tweets19.json')
df_20=create_df('tweets20.json')
df_21=create_df('tweets21.json')
df_22=create_df('tweets22.json')
df_23=create_df('tweets23.json')
df_24=create_df('tweets24.json')
df_25=create_df('tweets25.json')
df_26=create_df('tweets26.json')
df_27=create_df('tweets27.json')
df_28=create_df('tweets28.json')
df_29=create_df('tweets29.json')
df_30=create_df('tweets30.json')
df_31=create_df('tweets31.json')
df_32=create_df('tweets32.json')
df_33=create_df('tweets33.json')
df_34=create_df('tweets34.json')
df_35=create_df('tweets35.json')
df_36=create_df('tweets36.json')
df_37=create_df('tweets37.json')
df_38=create_df('tweets38.json')
df_39=create_df('tweets39.json')
df_40=create_df('tweets40.json')
df_41=create_df('tweets41.json')
df_42=create_df('tweets42.json')
df_43=create_df('tweets43.json')
df_44=create_df('tweets44.json')
df_45=create_df('tweets45.json')
df_46=create_df('tweets46.json')
df_47=create_df('tweets47.json')
df_48=create_df('tweets48.json')
df_49=create_df('tweets49.json')
df_50=create_df('tweets50.json')
df_51=create_df('tweets51.json')
df_52=create_df('tweets52.json')
df_53=create_df('tweets53.json')
df_54=create_df('tweets54.json')
df_55=create_df('tweets55.json')
df_56=create_df('tweets56.json')
df_57=create_df('tweets57.json')
df_58=create_df('tweets58.json')
df_59=create_df('tweets59.json')
df_60=create_df('tweets60.json')
df_61=create_df('tweets61.json')
df_62=create_df('tweets62.json')
df_63=create_df('tweets63.json')
df_64=create_df('tweets64.json')
df_65=create_df('tweets65.json')
df_66=create_df('tweets66.json')
df_67=create_df('tweets67.json')
df_68=create_df('tweets68.json')
df_69=create_df('tweets69.json')
df_70=create_df('tweets70.json')
df_71=create_df('tweets71.json')
df_72=create_df('tweets72.json')
df_73=create_df('tweets73.json')
df_74=create_df('tweets74.json')
df_75=create_df('tweets75.json')
df_76=create_df('tweets76.json')
df_77=create_df('tweets77.json')
df_78=create_df('tweets78.json')
df_79=create_df('tweets79.json')
df_80=create_df('tweets80.json')
df_81=create_df('tweets81.json')
df_82=create_df('tweets82.json')
df_83=create_df('tweets83.json')
df_84=create_df('tweets84.json')
df_85=create_df('tweets85.json')
df_86=create_df('tweets86.json')
df_87=create_df('tweets87.json')
df_88=create_df('tweets88.json')
df_89=create_df('tweets89.json')
df_90=create_df('tweets90.json')
df_91=create_df('tweets91.json')
df_92=create_df('tweets92.json')
df_93=create_df('tweets93.json')
df_94=create_df('tweets94.json')
df_95=create_df('tweets95.json')
df_96=create_df('tweets96.json')
df_97=create_df('tweets97.json')
df_98=create_df('tweets98.json')
df_99=create_df('tweets99.json')
df_100=create_df('tweets100.json')
df_101=create_df('tweets101.json')
df_102=create_df('tweets102.json')
df_103=create_df('tweets103.json')
df_104=create_df('tweets104.json')
df_105=create_df('tweets105.json')
df_106=create_df('tweets106.json')
df_107=create_df('tweets107.json')
df_108=create_df('tweets108.json')
df_109=create_df('tweets109.json')
df_110=create_df('tweets110.json')
df_111=create_df('tweets111.json')
df_112=create_df('tweets112.json')
df_113=create_df('tweets113.json')
df_114=create_df('tweets114.json')
df_115=create_df('tweets115.json')
df_116=create_df('tweets116.json')
df_117=create_df('tweets117.json')
df_118=create_df('tweets118.json')
df_119=create_df('tweets119.json')
df_120=create_df('tweets120.json')
df_121=create_df('tweets121.json')
df_122=create_df('tweets122.json')
df_123=create_df('tweets123.json')
df_124=create_df('tweets124.json')
df_125=create_df('tweets125.json')
df_126=create_df('tweets126.json')
df_127=create_df('tweets127.json')
df_128=create_df('tweets128.json')
df_129=create_df('tweets129.json')
df_130=create_df('tweets130.json')
df_131=create_df('tweets131.json')
df_132=create_df('tweets132.json')
df_133=create_df('tweets133.json')
df_134=create_df('tweets134.json')
df_135=create_df('tweets135.json')
df_136=create_df('tweets136.json')
df_137=create_df('tweets137.json')
df_138=create_df('tweets138.json')
df_139=create_df('tweets139.json')
df_140=create_df('tweets140.json')
df_141=create_df('tweets141.json')
df_142=create_df('tweets142.json')
df_143=create_df('tweets143.json')
df_144=create_df('tweets144.json')
df_145=create_df('tweets145.json')
df_146=create_df('tweets146.json')
df_147=create_df('tweets147.json')
df_148=create_df('tweets148.json')
df_149=create_df('tweets149.json')
df_150=create_df('tweets150.json')
df_151=create_df('tweets151.json')
df_152=create_df('tweets152.json')
df_153=create_df('tweets153.json')
df_154=create_df('tweets154.json')
df_155=create_df('tweets155.json')
df_156=create_df('tweets156.json')
df_157=create_df('tweets157.json')
df_158=create_df('tweets158.json')
df_159=create_df('tweets159.json')
df_160=create_df('tweets160.json')
df_161=create_df('tweets161.json')
df_162=create_df('tweets162.json')
df_163=create_df('tweets163.json')
df_164=create_df('tweets164.json')
df_165=create_df('tweets165.json')
df_166=create_df('tweets166.json')
df_167=create_df('tweets167.json')
df_168=create_df('tweets168.json')
df_169=create_df('tweets169.json')
df_170=create_df('tweets170.json')
df_171=create_df('tweets171.json')
df_172=create_df('tweets172.json')
df_173=create_df('tweets173.json')
df_174=create_df('tweets174.json')
df_175=create_df('tweets175.json')
df_176=create_df('tweets176.json')
df_177=create_df('tweets177.json')
df_178=create_df('tweets178.json')
df_179=create_df('tweets179.json')
df_180=create_df('tweets180.json')
df_181=create_df('tweets181.json')
df_182=create_df('tweets182.json')
df_183=create_df('tweets183.json')
df_184=create_df('tweets184.json')
df_185=create_df('tweets185.json')
df_186=create_df('tweets186.json')
df_187=create_df('tweets187.json')
df_188=create_df('tweets188.json')
df_189=create_df('tweets189.json')
df_190=create_df('tweets190.json')
df_191=create_df('tweets191.json')
df_192=create_df('tweets192.json')
df_193=create_df('tweets193.json')
df_194=create_df('tweets194.json')
df_195=create_df('tweets195.json')
df_196=create_df('tweets196.json')
df_197=create_df('tweets197.json')
df_198=create_df('tweets198.json')
df_199=create_df('tweets199.json')
df_200=create_df('tweets200.json')
df_201=create_df('tweets201.json')
df_202=create_df('tweets202.json')
df_203=create_df('tweets203.json')
df_204=create_df('tweets204.json')
df_205=create_df('tweets205.json')
df_206=create_df('tweets206.json')
df_207=create_df('tweets207.json')
df_208=create_df('tweets208.json')
df_209=create_df('tweets209.json')
df_210=create_df('tweets210.json')
df_211=create_df('tweets211.json')
df_212=create_df('tweets212.json')
df_213=create_df('tweets213.json')
df_214=create_df('tweets214.json')
df_215=create_df('tweets215.json')
df_216=create_df('tweets216.json')
df_217=create_df('tweets217.json')
df_218=create_df('tweets218.json')
df_219=create_df('tweets219.json')
df_220=create_df('tweets220.json')
df_221=create_df('tweets221.json')
df_222=create_df('tweets222.json')
df_223=create_df('tweets223.json')
df_224=create_df('tweets224.json')
df_225=create_df('tweets225.json')
df_226=create_df('tweets226.json')
df_227=create_df('tweets227.json')
df_228=create_df('tweets228.json')
df_229=create_df('tweets229.json')
df_230=create_df('tweets230.json')
df_231=create_df('tweets231.json')
df_232=create_df('tweets232.json')
df_233=create_df('tweets233.json')
df_234=create_df('tweets234.json')
df_235=create_df('tweets235.json')
df_236=create_df('tweets236.json')
df_237=create_df('tweets237.json')
df_238=create_df('tweets238.json')
df_239=create_df('tweets239.json')
df_240=create_df('tweets240.json')
df_241=create_df('tweets241.json')
df_242=create_df('tweets242.json')
df_243=create_df('tweets243.json')
df_244=create_df('tweets244.json')
df_245=create_df('tweets245.json')
df_246=create_df('tweets246.json')
df_247=create_df('tweets247.json')
df_248=create_df('tweets248.json')
df_249=create_df('tweets249.json')
df_250=create_df('tweets250.json')
df_251=create_df('tweets251.json')
df_252=create_df('tweets252.json')
df_253=create_df('tweets253.json')
df_254=create_df('tweets254.json')

In [5]:
df_125.head()

,tweet_id,user_id,display_name,screen_name,tweet_date,main_text,fav_count,rt_count,followers_count,is_verified,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,retweet_text,retweet_id,retweet_user_id,retweet_screen_name,retweet_is_verified,retweet_fav_count,retweet_followers_count,quoted_text,quoted_id,quoted_user_id,quoted_screen_name,quoted_is_verified,quoted_fav_count,is_retweet,is_quote
0,1108496728062337025,806625064993116161,Girlwithopinion,janiszilly,Wed Mar 20 22:33:09 +0000 2019,RT @CyrusMMcQueen: Trump attacks Obama’s intel...,0,2509,8141,False,NaN,NaN,None,Trump attacks Obama’s intelligence because he ...,1.108466e+18,1.446853e+09,CyrusMMcQueen,False,10098.0,102441.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
1,1108496727902871553,122792034,DC,dcutler1958,Wed Mar 20 22:33:09 +0000 2019,RT @RBReich: Here's a reminder of what Trump w...,0,2064,255,False,NaN,NaN,None,Here's a reminder of what Trump was doing duri...,1.108474e+18,1.485297e+08,RBReich,True,4566.0,661995.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
2,1108496727882059776,1078345467904344065,Girly,Girly89637649,Wed Mar 20 22:33:09 +0000 2019,RT @funder: I just wanna state for the record ...,0,6379,48,False,NaN,NaN,None,I just wanna state for the record that Sen Lin...,1.108490e+18,1.424724e+07,funder,True,20021.0,450308.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
3,1108496727756206080,1631358120,Cheryl Keller,mindfulone1500,Wed Mar 20 22:33:09 +0000 2019,RT @Libertea2012: Trump knows ‘he’s losing to ...,0,3,174,False,NaN,NaN,None,Trump knows ‘he’s losing to John McCain and ca...,1.108491e+18,6.075584e+08,Libertea2012,False,2.0,52508.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
4,1108496727579992069,1021734138,KP Ruppel,Ruppelkp,Wed Mar 20 22:33:09 +0000 2019,RT @AlbertBrooks: Listening to Trump continuin...,0,2550,559,False,NaN,NaN,None,Listening to Trump continuing to trash John Mc...,1.108455e+18,2.632925e+08,AlbertBrooks,True,17406.0,1744958.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0

In [6]:
def concat_dfs(num):
    x = 0
    df_list = []
    while x < num:
        df_list.append(f'df_{x}')
        x +=1
    return df_list

In [7]:
df_list = [df_0,
 df_1,
 df_2,
 df_3,
 df_4,
 df_5,
 df_6,
 df_7,
 df_8,
 df_9,
 df_10,
 df_11,
 df_12,
 df_13,
 df_14,
 df_15,
 df_16,
 df_17,
 df_18,
 df_19,
 df_20,
 df_21,
 df_22,
 df_23,
 df_24,
 df_25,
 df_26,
 df_27,
 df_28,
 df_29,
 df_30,
 df_31,
 df_32,
 df_33,
 df_34,
 df_35,
 df_36,
 df_37,
 df_38,
 df_39,
 df_40,
 df_41,
 df_42,
 df_43,
 df_44,
 df_45,
 df_46,
 df_47,
 df_48,
 df_49,
 df_50,
 df_51,
 df_52,
 df_53,
 df_54,
 df_55,
 df_56,
 df_57,
 df_58,
 df_59,
 df_60,
 df_61,
 df_62,
 df_63,
 df_64,
 df_65,
 df_66,
 df_67,
 df_68,
 df_69,
 df_70,
 df_71,
 df_72,
 df_73,
 df_74,
 df_75,
 df_76,
 df_77,
 df_78,
 df_79,
 df_80,
 df_81,
 df_82,
 df_83,
 df_84,
 df_85,
 df_86,
 df_87,
 df_88,
 df_89,
 df_90,
 df_91,
 df_92,
 df_93,
 df_94,
 df_95,
 df_96,
 df_97,
 df_98,
 df_99,
 df_100,
 df_101,
 df_102,
 df_103,
 df_104,
 df_105,
 df_106,
 df_107,
 df_108,
 df_109,
 df_110,
 df_111,
 df_112,
 df_113,
 df_114,
 df_115,
 df_116,
 df_117,
 df_118,
 df_119,
 df_120,
 df_121,
 df_122,
 df_123,
 df_124,
 df_125,
 df_126,
 df_127,
 df_128,
 df_129,
 df_130,
 df_131,
 df_132,
 df_133,
 df_134,
 df_135,
 df_136,
 df_137,
 df_138,
 df_139,
 df_140,
 df_141,
 df_142,
 df_143,
 df_144,
 df_145,
 df_146,
 df_147,
 df_148,
 df_149,
 df_150,
 df_151,
 df_152,
 df_153,
 df_154,
 df_155,
 df_156,
 df_157,
 df_158,
 df_159,
 df_160,
 df_161,
 df_162,
 df_163,
 df_164,
 df_165,
 df_166,
 df_167,
 df_168,
 df_169,
 df_170,
 df_171,
 df_172,
 df_173,
 df_174,
 df_175,
 df_176,
 df_177,
 df_178,
 df_179,
 df_180,
 df_181,
 df_182,
 df_183,
 df_184,
 df_185,
 df_186,
 df_187,
 df_188,
 df_189,
 df_190,
 df_191,
 df_192,
 df_193,
 df_194,
 df_195,
 df_196,
 df_197,
 df_198,
 df_199,
 df_200,
 df_201,
 df_202,
 df_203,
 df_204,
 df_205,
 df_206,
 df_207,
 df_208,
 df_209,
 df_210,
 df_211,
 df_212,
 df_213,
 df_214,
 df_215,
 df_216,
 df_217,
 df_218,
 df_219,
 df_220,
 df_221,
 df_222,
 df_223,
 df_224,
 df_225,
 df_226,
 df_227,
 df_228,
 df_229,
 df_230,
 df_231,
 df_232,
 df_233,
 df_234,
 df_235,
 df_236,
 df_237,
 df_238,
 df_239,
 df_240,
 df_241,
 df_242,
 df_243,
 df_244,
 df_245,
 df_246,
 df_247,
 df_248,
 df_249,
 df_250,
 df_251,
 df_252,
 df_253,
 df_254]

In [8]:
final_mccain_df = pd.concat(df_list)

In [9]:
final_mccain_df.shape

(1037841, 28)

In [10]:
final_mccain_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1037841 entries, 0 to 4071
Data columns (total 28 columns):
tweet_id                   1037841 non-null int64
user_id                    1037841 non-null int64
display_name               1037841 non-null object
screen_name                1037841 non-null object
tweet_date                 1037841 non-null object
main_text                  1037841 non-null object
fav_count                  1037841 non-null int64
rt_count                   1037841 non-null int64
followers_count            1037841 non-null int64
is_verified                1037841 non-null bool
reply_to_tweet_id          70818 non-null float64
reply_to_user_id           81418 non-null float64
reply_to_screen_name       81418 non-null object
retweet_text               895858 non-null object
retweet_id                 895858 non-null float64
retweet_user_id            895858 non-null float64
retweet_screen_name        895858 non-null object
retweet_is_verified        895858 non-null object
retweet_fav_count          895858 non-null float64
retweet_followers_count    895858 non-null float64
quoted_text                13121 non-null object
quoted_id                  13121 non-null float64
quoted_user_id             13121 non-null float64
quoted_screen_name         13121 non-null object
quoted_is_verified         13121 non-null object
quoted_fav_count           13121 non-null float64
is_retweet                 1037841 non-null int64
is_quote                   1037841 non-null int64
dtypes: bool(1), float64(9), int64(7), object(11)
memory usage: 222.7+ MB

In [11]:
final_mccain_df.head()

,tweet_id,user_id,display_name,screen_name,tweet_date,main_text,fav_count,rt_count,followers_count,is_verified,reply_to_tweet_id,reply_to_user_id,reply_to_screen_name,retweet_text,retweet_id,retweet_user_id,retweet_screen_name,retweet_is_verified,retweet_fav_count,retweet_followers_count,quoted_text,quoted_id,quoted_user_id,quoted_screen_name,quoted_is_verified,quoted_fav_count,is_retweet,is_quote
0,1109131638112432129,113817127,KDW,WYATT251,Fri Mar 22 16:36:03 +0000 2019,RT @thedilleyshow: Donald J. Trump is still Pr...,0,107,474,False,NaN,NaN,None,Donald J. Trump is still President.\n\nHillary...,1.109098e+18,1.085581e+18,thedilleyshow,False,299.0,8815.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
1,1109131636262744066,4839872717,Lou Ella Howard,ellahoward271,Fri Mar 22 16:36:03 +0000 2019,RT @LindseyGrahamSC: Great read. Spot on.\n\n...,0,65,3601,False,NaN,NaN,None,Great read. Spot on.\n\nMuch more could be sa...,1.109117e+18,4.328953e+08,LindseyGrahamSC,True,181.0,756904.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
2,1109131635742564352,881906625799266304,God Is LOVE,janetlchatham,Fri Mar 22 16:36:03 +0000 2019,RT @LouDobbs: #TrumpTrain- @RealDonaldTrump is...,0,158,153,False,NaN,NaN,None,#TrumpTrain- @RealDonaldTrump is speaking out ...,1.109129e+18,2.648717e+07,LouDobbs,True,366.0,1901004.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
3,1109131633603440640,242425184,Dominika Markova,dominikam42,Fri Mar 22 16:36:02 +0000 2019,RT @votevets: 1. John McCain was a war hero.\n...,0,17392,198,False,NaN,NaN,None,1. John McCain was a war hero.\n\n2. John McCa...,1.108447e+18,1.651334e+07,votevets,True,62408.0,158248.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0
4,1109131633293037574,17200919,Michael Little,uzererr,Fri Mar 22 16:36:02 +0000 2019,RT @brithume: President Trump’s attacks on the...,0,1521,74,False,NaN,NaN,None,President Trump’s attacks on the late John McC...,1.109097e+18,1.120478e+08,brithume,True,9022.0,996715.0,NaN,NaN,NaN,NaN,NaN,NaN,1,0

In [12]:
# Out of the 509k million tweets, 4704 are from verified users
(final_mccain_df['is_verified'] == True).sum()

8580

In [13]:
# Out of the 509k million tweets, 359957 are retweets
(final_mccain_df['is_retweet'] == 1).sum()

895858

In [14]:
# Out of the 509k million tweets, 13190 are quotes
(final_mccain_df['is_quote'] == 1).sum()

13121

Now I will try to de-duplicate by tweet ID, to make sure I don't have duplicate rows

In [15]:
# All tweets in the dataset are unique
final_mccain_df['tweet_id'].nunique()

1037841

In [16]:
# There are 214055 unique users that have tweeted
final_mccain_df['user_id'].nunique()

341515

Pickling my final raw df for safe keeping

In [17]:
with open('/Users/robertpagano/metis_data/project_5/final_raw_mccain_df.pickle', 'wb') as to_write:
    pickle.dump(final_mccain_df, to_write)

I want to look at users who 100% retweet, and check how many there are for various counts. so for example, if a user has say 50 retweets in the last week, and no original tweets, this person is likely either a bot, or someone that no one else is ever really connecting to. Not relevant to my analysis

In [21]:
# df_tucker_verified = final_tucker_df[final_tucker_df['is_verified'] == True]

In [22]:
# df_tucker_verified.shape

(4704, 28)

In [23]:
# df_tucker_verified.nunique()

tweet_id                   4704
user_id                    1955
display_name               1954
screen_name                1955
tweet_date                 4657
main_text                  3333
fav_count                   525
rt_count                    444
followers_count            2850
is_verified                   1
reply_to_tweet_id           593
reply_to_user_id            438
reply_to_screen_name        438
retweet_text                957
retweet_id                  962
retweet_user_id             626
retweet_screen_name         626
retweet_is_verified           2
retweet_fav_count           596
retweet_followers_count    1031
quoted_text                 202
quoted_id                   202
quoted_user_id              153
quoted_screen_name          153
quoted_is_verified            2
quoted_fav_count            177
is_retweet                    2
is_quote                      2
dtype: int64

In [24]:
# with open('/Users/robertpagano/metis_data/project_5/df_tucker_verified.pickle', 'wb') as to_write:
#     pickle.dump(df_tucker_verified, to_write)